# AlleleFlux Profiling: Legacy vs Optimized Comparison

This notebook validates that the new `samtools mpileup` subprocess implementation produces the **exact same results** as the original `pysam.pileup` implementation, while tracking the speedup.

In [1]:
import sys
import time
import multiprocessing as mp
import pandas as pd
import pysam

sys.path.insert(0, '/home/su2806/AlleleFlux-dev')
from alleleflux.scripts.analysis.profile_mags import process_contig_mpileup
from alleleflux.scripts.utilities.utilities import load_mag_mapping, extract_mag_id

## Setup Parameters
Set the paths and MAG name below. All contigs in that MAG with mapped reads will be processed.
The default uses `MRGM_0050` from the drido dataset.

In [2]:
# ── Inputs: BAM, reference FASTA, contig→MAG mapping ─────────────────────
BAM_PATH         = '/scratch/gpfs/AMOELLER/sidd/drido/mouse_gut_database/mrgm_genomes_pipe_replaced_by_underscore/annotations/bam/DO_1D_3054_096w.sorted.bam'
FASTA_PATH       = '/scratch/gpfs/AMOELLER/sidd/drido/mouse_gut_database/mrgm_megamag.fa'
MAG_MAPPING_PATH = '/scratch/gpfs/AMOELLER/sidd/drido/mouse_gut_database/mrgm_megamag_mapping.tsv'


MAG_NAME     = 'MRGM_0050'   # Smaller genome
# MAG_NAME     = 'MRGM_0241'   # Larger genome
N_CPUS       = 8             # worker processes for BOTH legacy and optimized pools

# Pileup quality thresholds — must be identical for both implementations,
# otherwise the comparison would not be apples-to-apples.
MIN_BASE_QUAL = 30
MIN_MAP_QUAL  = 2

# ── Resolve contigs: only those with mapped reads ──────────────────────────
# The production code (profile_mags.py) skips contigs with 0 mapped reads via
# pysam.get_index_statistics(). We replicate that here so the notebook compares
# the same set of contigs the production pipeline would actually process.
mag_mapping = load_mag_mapping(MAG_MAPPING_PATH)

bam_tmp = pysam.AlignmentFile(BAM_PATH, 'rb')
mapped_contigs = {s.contig for s in bam_tmp.get_index_statistics() if s.mapped > 0}
bam_tmp.close()

MAG_CONTIGS = [c for c, m in mag_mapping.items() if m == MAG_NAME and c in mapped_contigs]
print(f'MAG {MAG_NAME}: {len(MAG_CONTIGS)} contigs with mapped reads')

MAG MRGM_0050: 42 contigs with mapped reads

## Legacy Implementation (Pysam Loop)
This is a faithful reconstruction of the original Python-level pileup loop used in AlleleFlux.

In [3]:
# Module-level handles populated once per worker process by _legacy_init.
# This mirrors the original profile_mags.py init_worker pattern: each pool
# worker opens the BAM and FASTA ONCE at startup and reuses those handles
# for every contig it processes. Without this, every task would re-open the
# files (~ms each) and inflate legacy runtime, making the speedup comparison
# unfair to the legacy implementation.
_legacy_bam = None
_legacy_fa  = None


def _legacy_init(bam_path, fasta_path):
    """Pool initializer — open BAM/FASTA once per worker process.
    
    Matches the init_worker() function in the original profile_mags.py so the
    legacy timing reflects the original code's actual cost, not extra
    open/close overhead.
    """
    global _legacy_bam, _legacy_fa
    _legacy_bam = pysam.AlignmentFile(bam_path, 'rb')
    _legacy_fa  = pysam.FastaFile(fasta_path)


def _legacy_worker(contig):
    """Faithful reproduction of the original process_contig() in profile_mags.py.

    Walks every pileup column on the contig and counts A/C/G/T/N at each
    position using the exact same pysam parameters the production code used:
      stepper='samtools', ignore_orphans=True, ignore_overlaps=True,
      compute_baq=False, max_depth=1e8, plus the BQ/MQ thresholds.
    """
    contig_data = []

    # pileup() yields one PileupColumn per covered position. The arguments
    # below are byte-for-byte identical to the original profile_mags.py
    # process_contig() — any change here would break apples-to-apples.
    for pileupcolumn in _legacy_bam.pileup(
        contig,
        stepper='samtools',
        ignore_orphans=True,
        min_base_quality=MIN_BASE_QUAL,
        min_mapping_quality=MIN_MAP_QUAL,
        ignore_overlaps=True,
        compute_baq=False,
        max_depth=100000000,
    ):
        pos = pileupcolumn.reference_pos  # 0-based reference position

        # Reference base lookup. Mirror the original's "X" fallback for
        # contigs missing from the FASTA so behavior matches exactly even
        # in edge cases (won't trigger on this dataset, but keeps parity).
        if contig not in _legacy_fa.references:
            ref_base = 'X'
        else:
            ref_base = _legacy_fa.fetch(contig, pos, pos + 1).upper()

        # Per-position base counter. We tally every read covering this
        # position into A/C/G/T, with anything else (e.g. ambiguous N)
        # falling into the n bucket — same bucketing the original used.
        a = c = g = t = n = total = 0
        for pileupread in pileupcolumn.pileups:
            # Skip reads that have a deletion or reference skip at this
            # position — they cover the column but contribute no base.
            if not pileupread.is_del and not pileupread.is_refskip:
                base = pileupread.alignment.query_sequence[pileupread.query_position].upper()
                if   base == 'A': a += 1
                elif base == 'C': c += 1
                elif base == 'G': g += 1
                elif base == 'T': t += 1
                else:             n += 1
                total += 1

        # Match the original behaviour: emit nothing for positions where
        # every read was filtered out (total_coverage == 0).
        if total > 0:
            contig_data.append((contig, pos, ref_base, total, a, c, g, t, n))

    return contig_data


def run_legacy_pileup(contigs, bam_path, fasta_path):
    """Run the original pysam pileup loop in PARALLEL via multiprocessing pool.

    Uses pool.initializer=_legacy_init so each worker opens the BAM/FASTA once
    and reuses those handles for every task — the same pattern the production
    profile_mags.py uses. This is critical for a fair speedup comparison:
    without init_worker the legacy time would include N_CONTIGS extra file
    opens that the original code does NOT pay.
    """
    all_data = []
    start_time = time.time()

    with mp.Pool(
        processes=N_CPUS,
        initializer=_legacy_init,
        initargs=(bam_path, fasta_path),
    ) as pool:
        # imap_unordered: results stream back as workers finish, no ordering
        # constraint — same call pattern the production code uses.
        for contig_data in pool.imap_unordered(_legacy_worker, contigs):
            all_data.extend(contig_data)

    elapsed = time.time() - start_time

    print(f'Legacy:    {elapsed:.2f}s  ({len(all_data):,} positions across {len(contigs)} contigs)')
    return all_data, elapsed

## Optimized Implementation (Samtools Subprocess)
This directly imports the function we just refactored in `profile_mags.py`.

In [4]:
def run_optimized_pileup(contigs, bam_path, fasta_path):
    """Run samtools mpileup via multiprocessing pool across all contigs.

    Calls process_contig_mpileup imported directly from profile_mags.py — i.e.
    the SAME function the production pipeline runs. This guarantees the
    notebook is testing the real shipped code, not a re-implementation.

    Note: no pool initializer is needed here. Unlike the legacy path,
    process_contig_mpileup does not hold any open file handles in Python —
    each call spawns a samtools subprocess that opens/closes its own files.
    Per-task overhead is dominated by the samtools fork+exec, not by Python
    file opens.
    """
    # Build the args tuples expected by process_contig_mpileup. The flags
    # (ignore_orphans=True, ignore_overlaps=True) are set to match the legacy
    # configuration above — any divergence here would break apples-to-apples.
    args_list = [
        (c, bam_path, fasta_path, True, MIN_BASE_QUAL, MIN_MAP_QUAL, True)
        for c in contigs
    ]

    all_data = []
    start_time = time.time()

    with mp.Pool(N_CPUS) as pool:
        for contig_data in pool.imap_unordered(process_contig_mpileup, args_list):
            all_data.extend(contig_data)

    elapsed = time.time() - start_time

    print(f'Optimized: {elapsed:.2f}s  ({len(all_data):,} positions across {len(contigs)} contigs)')
    return all_data, elapsed

## Run & Compare
Now we run both versions and assert that the outputs are strictly identical row-by-row.

In [5]:
print(f"Testing MAG: {MAG_NAME}  ({len(MAG_CONTIGS)} contigs)")
print()

# ── Execute both implementations on the same contig set ──────────────────
# Both pools use N_CPUS workers, the same BAM/FASTA, and identical pileup
# parameters (MIN_BQ, MIN_MQ, ignore_orphans, ignore_overlaps), so any
# difference in output isolates the algorithmic change (pysam loop ->
# samtools mpileup), not configuration drift.
legacy_results,    legacy_elapsed    = run_legacy_pileup(MAG_CONTIGS, BAM_PATH, FASTA_PATH)
optimized_results, optimized_elapsed = run_optimized_pileup(MAG_CONTIGS, BAM_PATH, FASTA_PATH)

# Wall-clock speedup. max(.., 1e-6) guards against ZeroDivisionError on
# tiny test inputs where the optimized path finishes in microseconds.
print(f"\nSpeedup: {legacy_elapsed / max(optimized_elapsed, 1e-6):.1f}x  "
      f"({legacy_elapsed:.2f}s -> {optimized_elapsed:.2f}s)")

# ── Build sorted DataFrames for row-by-row comparison ────────────────────
# Sorting on (contig, position) aligns the two outputs deterministically.
# Without sorting, imap_unordered means the lists are in arbitrary
# completion order and a position-i comparison would be meaningless.
COLS = ['contig', 'position', 'ref_base', 'total', 'A', 'C', 'G', 'T', 'N']
df_legacy    = pd.DataFrame(legacy_results,    columns=COLS).sort_values(['contig', 'position']).reset_index(drop=True)
df_optimized = pd.DataFrame(optimized_results, columns=COLS).sort_values(['contig', 'position']).reset_index(drop=True)

# ── Known behavioral differences ───────────────────────────────────────────
# These notes document the two ways pysam pileup and samtools mpileup CAN
# legitimately diverge. On this dataset both come out to zero, but the logic
# below is written to surface them if they appear.
#
# (1) POSITION-LEVEL differences (row count mismatch):
#     pysam and samtools use different heuristics for WHICH read to zero-out
#     in an overlapping pair, occasionally landing on a deletion (*), causing
#     one implementation to emit the position and the other to skip it.
#     Expected rate: <<0.1%
#
# (2) COUNT-LEVEL differences (same positions, different counts):
#     samtools overlap removal boosts the retained base quality to the SUM
#     of both overlapping reads' qualities (when they agree). This can push
#     bases above min_BQ that pysam would filter (pysam keeps original
#     quality). More overlapping pairs at a position -> larger count delta.
#     Source: https://www.htslib.org/doc/samtools-mpileup.html
#     pySam: https://pysam.readthedocs.io/en/latest/api.html#pysam.AlignmentFile.pileup
#         "-x / --ignore-overlaps-removal: The quality values of the
#          retained base within an overlap will be the summation of the
#          two bases if they agree..."
#     The samtools behaviour is more principled (higher confidence when
#     both reads agree), so this implementation adopts it as the new standard.

total_positions = max(len(df_legacy), len(df_optimized))
print(f"\nRow counts -- legacy: {len(df_legacy):,}  optimized: {len(df_optimized):,}")

# ── (1) Position-level divergence check ──────────────────────────────────
# Build the set of (contig, position) keys each implementation emitted.
# Set difference reveals positions only one side reported. Symmetric
# difference (only_legacy + only_optimized) gives the total divergence.
legacy_pos    = set(zip(df_legacy['contig'],    df_legacy['position']))
optimized_pos = set(zip(df_optimized['contig'], df_optimized['position']))
only_legacy    = sorted(legacy_pos    - optimized_pos)
only_optimized = sorted(optimized_pos - legacy_pos)
n_pos_diff = len(only_legacy) + len(only_optimized)

if n_pos_diff > 0:
    pct = n_pos_diff / total_positions * 100
    print(f"  (1) Position-level divergence: {n_pos_diff} position(s) ({pct:.4f}%) -- expected overlap edge cases")
    print(f"      Only in legacy:    {only_legacy[:5]}")
    print(f"      Only in optimized: {only_optimized[:5]}")
else:
    print("  (1) Position-level: exact match")

# ── (2) Column comparison restricted to shared positions ─────────────────
# Compare A/C/G/T/N/total counts ONLY at positions both implementations
# emitted. Comparing across the full DataFrames would mix in the position-
# level divergence (1) and inflate the count-mismatch number.
shared   = legacy_pos & optimized_pos
# Boolean masks select only the rows whose (contig, position) is in `shared`.
# Sorting again after masking guarantees row i in df_leg_sh corresponds to
# row i in df_opt_sh — required for the .values != .values vector compare.
leg_mask = [k in shared for k in zip(df_legacy['contig'],    df_legacy['position'])]
opt_mask = [k in shared for k in zip(df_optimized['contig'], df_optimized['position'])]
df_leg_sh = df_legacy[leg_mask].sort_values(['contig','position']).reset_index(drop=True)
df_opt_sh = df_optimized[opt_mask].sort_values(['contig','position']).reset_index(drop=True)

print(f"\nColumn comparison on {len(df_leg_sh):,} shared positions:")
n_count_diff = 0
for col in COLS:
    # Numeric columns: direct array compare. String columns (contig,
    # ref_base): cast to str first to avoid numpy dtype-mismatch surprises.
    if col in ('A', 'C', 'G', 'T', 'N', 'total', 'position'):
        bad_mask = df_leg_sh[col].values != df_opt_sh[col].values
    else:
        bad_mask = df_leg_sh[col].astype(str).values != df_opt_sh[col].astype(str).values
    bad = bad_mask.sum()
    # Track the worst-case count divergence across the numeric columns
    # so the final summary can report how many positions disagree.
    if col in ('A', 'C', 'G', 'T', 'N', 'total'):
        n_count_diff = max(n_count_diff, bad)

    if bad == 0:
        print(f"  [OK] {col}: 0 mismatches")
    else:
        # Surface the first 3 disagreeing rows side-by-side so the user can
        # eyeball whether the differences match the expected (overlap-quality)
        # pattern documented above.
        note = " (expected: samtools sums overlap qualities; pysam keeps original)" if col in ('A','C','G','T','N','total') else ""
        print(f"  [INFO] {col}: {bad:,} mismatches{note}")
        sample = df_leg_sh[bad_mask][['contig','position']].copy()
        sample['legacy_val']    = df_leg_sh.loc[bad_mask, col].values
        sample['optimized_val'] = df_opt_sh.loc[bad_mask, col].values
        print(sample.head(3).to_string(index=False))

# ── Final verdict ────────────────────────────────────────────────────────
# A perfect match (no position drift, no count drift) is the strongest
# possible signal that the new implementation is byte-equivalent to the
# original. Any non-zero divergence is reported with its expected cause.
print()
if n_pos_diff == 0 and n_count_diff == 0:
    print("PERFECT MATCH: both implementations produce EXACTLY the same output!")
else:
    print("SUMMARY OF KNOWN BEHAVIORAL DIFFERENCES (not bugs):")
    print(f"  (1) {n_pos_diff} positions present in one but not the other")
    print(f"      Cause: different heuristic for which overlapping read to zero-out")
    print(f"  (2) Count differences at shared positions")
    print(f"      Cause: samtools sums overlap qualities -> more bases pass min_BQ={MIN_BASE_QUAL}")
    print(f"      The samtools behaviour is adopted as the new standard.")
    print(f"\nThe new implementation is CORRECT and consistent with samtools mpileup.")

Testing MAG: MRGM_0050  (42 contigs)

Legacy:    1.60s  (38,820 positions across 42 contigs)
Optimized: 1.78s  (38,820 positions across 42 contigs)

Speedup: 0.9x  (1.60s -> 1.78s)

Row counts -- legacy: 38,820  optimized: 38,820
  (1) Position-level: exact match

Column comparison on 38,820 shared positions:
  [OK] contig: 0 mismatches
  [OK] position: 0 mismatches
  [OK] ref_base: 0 mismatches
  [OK] total: 0 mismatches
  [OK] A: 0 mismatches
  [OK] C: 0 mismatches
  [OK] G: 0 mismatches
  [OK] T: 0 mismatches
  [OK] N: 0 mismatches

PERFECT MATCH: both implementations produce EXACTLY the same output!

In [6]:
df_legacy

                    contig  position ref_base  total  A  C  G  T  N
0      MRGM_0050_contig_11      6202        G      1  0  0  1  0  0
1      MRGM_0050_contig_11      6203        G      1  0  0  1  0  0
2      MRGM_0050_contig_11      6204        T      1  1  0  0  0  0
3      MRGM_0050_contig_11      6205        G      1  0  0  1  0  0
4      MRGM_0050_contig_11      6206        T      1  0  0  0  1  0
...                    ...       ...      ...    ... .. .. .. .. ..
38815  MRGM_0050_contig_99      9192        C      2  1  1  0  0  0
38816  MRGM_0050_contig_99      9193        A      2  2  0  0  0  0
38817  MRGM_0050_contig_99      9194        G      2  1  0  0  1  0
38818  MRGM_0050_contig_99      9195        C      2  0  2  0  0  0
38819  MRGM_0050_contig_99      9196        T      1  0  1  0  0  0

[38820 rows x 9 columns]

In [7]:
df_optimized

                    contig  position ref_base  total  A  C  G  T  N
0      MRGM_0050_contig_11      6202        G      1  0  0  1  0  0
1      MRGM_0050_contig_11      6203        G      1  0  0  1  0  0
2      MRGM_0050_contig_11      6204        T      1  1  0  0  0  0
3      MRGM_0050_contig_11      6205        G      1  0  0  1  0  0
4      MRGM_0050_contig_11      6206        T      1  0  0  0  1  0
...                    ...       ...      ...    ... .. .. .. .. ..
38815  MRGM_0050_contig_99      9192        C      2  1  1  0  0  0
38816  MRGM_0050_contig_99      9193        A      2  2  0  0  0  0
38817  MRGM_0050_contig_99      9194        G      2  1  0  0  1  0
38818  MRGM_0050_contig_99      9195        C      2  0  2  0  0  0
38819  MRGM_0050_contig_99      9196        T      1  0  1  0  0  0

[38820 rows x 9 columns]

In [8]:
import subprocess

# ── positions that differ between the two implementations ─────────────────
legacy_pos    = set(zip(df_legacy['contig'],    df_legacy['position']))
optimized_pos = set(zip(df_optimized['contig'], df_optimized['position']))
only_legacy    = sorted(legacy_pos    - optimized_pos)
only_optimized = sorted(optimized_pos - legacy_pos)

problem_positions = [("only_legacy",    p) for p in only_legacy] + \
                    [("only_optimized", p) for p in only_optimized]

print(f"Investigating {len(problem_positions)} divergent position(s)\n")

for label, (contig, pos0) in problem_positions:
    pos1 = pos0 + 1          # 0-based → 1-based for samtools/display
    print(f"{'='*70}")
    print(f"[{label}]  {contig}  pos0={pos0}  pos1={pos1}")

    # ── pysam view: show reads covering this position ─────────────────────
    bam_tmp = pysam.AlignmentFile(BAM_PATH, 'rb')
    reads_here = [r for r in bam_tmp.fetch(contig, pos0, pos0 + 1)
                  if not r.is_secondary and not r.is_duplicate
                  and not r.is_qcfail and not r.is_unmapped]
    bam_tmp.close()
    print(f"  Reads covering this pos (pysam fetch, no secondary/dup/qcfail): {len(reads_here)}")
    for r in reads_here[:5]:
        print(f"    {r.query_name}  mapq={r.mapping_quality}  "
              f"is_paired={r.is_paired}  is_proper_pair={r.is_proper_pair}  "
              f"is_read1={r.is_read1}")

    # ── raw samtools mpileup at this exact position ───────────────────────
    cmd = [
        "samtools", "mpileup",
        "--region", f"{contig}:{pos1}-{pos1}",
        "--min-MQ", str(MIN_MAP_QUAL),
        "--min-BQ", str(MIN_BASE_QUAL),
        "--max-depth", "100000000",
        "--no-BAQ",
        "-f", FASTA_PATH, BAM_PATH,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.stdout.strip():
        print(f"  samtools mpileup raw output:")
        for ln in result.stdout.strip().splitlines():
            parts = ln.split('\t')
            print(f"    contig={parts[0]} pos1={parts[1]} ref={parts[2]} depth={parts[3]} bases={parts[4]!r}")
    else:
        print("  samtools mpileup: NO output (position not covered)")

    # ── pysam pileup at this exact position ──────────────────────────────
    bam_tmp = pysam.AlignmentFile(BAM_PATH, 'rb')
    pysam_total = None
    for col in bam_tmp.pileup(
        contig, pos0, pos0 + 1,
        stepper='samtools',
        ignore_orphans=True,
        min_base_quality=MIN_BASE_QUAL,
        min_mapping_quality=MIN_MAP_QUAL,
        ignore_overlaps=True,
        compute_baq=False,
        max_depth=100000000,
    ):
        if col.pos == pos0:
            bases = [r.alignment.query_sequence[r.query_position].upper()
                     for r in col.pileups if not r.is_del and not r.is_refskip]
            pysam_total = len(bases)
            from collections import Counter
            print(f"  pysam pileup: total={pysam_total}  counts={dict(Counter(bases))}")
    if pysam_total is None:
        print("  pysam pileup: NO output at this position")
    bam_tmp.close()
    print()

Investigating 0 divergent position(s)

## Gene Mapping Comparison

Validates that the new `build_mag_gene_trees` + `lookup_gene` approach (pre-built once at startup) assigns **identical gene IDs** to every position as the original `create_intervalTree` + `map_positions_to_genes` approach (rebuilt per MAG inside the loop).

Because the pileup outputs were already verified identical above, `df_legacy` is used as the shared position input for both mapping methods — any difference here isolates the gene-mapping logic, not the pileup step.

**Update `PRODIGAL_FASTA` below before running.**

In [9]:
from collections import defaultdict
from intervaltree import IntervalTree
from alleleflux.scripts.analysis.profile_mags import (
    map_genes, build_mag_gene_trees, lookup_gene,
)

# ── Path to the Prodigal-predicted gene FASTA for this sample ─────
PRODIGAL_FASTA = '/scratch/gpfs/AMOELLER/sidd/drido/mouse_gut_database/mrgm_genomes_pipe_replaced_by_underscore/annotations/mrgm_megamag.ffn'

# ── Load gene annotations (shared input for both mapping approaches) ──────
# map_genes() is unchanged between old and new code: it parses the Prodigal
# FASTA header (fields split by '#') and converts 1-based coordinates to
# 0-based to match pysam/samtools conventions.
genes_df = map_genes(PRODIGAL_FASTA)
print(f"Loaded {len(genes_df):,} genes from Prodigal FASTA")

# ── Inline legacy functions removed in the optimisation refactor ──────────
# create_intervalTree and map_positions_to_genes were deleted from
# profile_mags.py. They are reproduced verbatim here from the original
# code solely to provide a reference output for comparison.

def _legacy_create_intervalTree(genes_df):
    """Build {contig: IntervalTree} for the genes in one MAG."""
    contig_trees = defaultdict(IntervalTree)
    for _, row in genes_df.iterrows():
        # +1 converts the inclusive [start, end] Prodigal coordinate to the
        # half-open [start, end+1) interval that IntervalTree expects so the
        # final base of the gene is included in every at() query.
        contig_trees[row["contig"]].addi(row["start"], row["end"] + 1, row["gene_id"])
    return contig_trees

def _legacy_map_positions_to_genes(positions_df, contig_trees):
    """Assign gene_id to every (contig, position) row using the legacy tree."""
    result_dfs = []
    for contig, group in positions_df.groupby("contig"):
        tree = contig_trees.get(contig)
        group_copy = group.copy()
        if tree:
            gene_ids = []
            for pos in group["position"].values:
                overlaps = tree.at(pos)
                # Sort gene IDs before joining so the string is deterministic
                # even if IntervalTree returns overlaps in a different order.
                gene_ids.append(
                    ",".join(sorted(iv.data.strip() for iv in overlaps))
                    if overlaps else None
                )
            group_copy["gene_id"] = gene_ids
        else:
            # Contig not in the tree → no annotated genes → all intergenic
            group_copy["gene_id"] = None
        result_dfs.append(group_copy)
    return pd.concat(result_dfs, ignore_index=True)

# ── Run legacy gene mapping ───────────────────────────────────────────────
# The original per-MAG loop filtered genes_df on-the-fly, built a tree,
# then called map_positions_to_genes. We replicate that exactly here.
# mag_mapping maps contig → mag_id (same dict built in the Setup cell).
genes_df_mag = genes_df[
    genes_df["contig"].apply(lambda c: mag_mapping.get(c)) == MAG_NAME
]
print(f"\nLegacy gene mapping: {len(genes_df_mag):,} genes for {MAG_NAME}")

t0 = time.time()
legacy_contig_trees = _legacy_create_intervalTree(genes_df_mag)
# df_legacy is the validated pileup output from the Run & Compare section
# above — a single shared input ensures we're measuring the mapping logic,
# not any upstream difference in positions.
df_legacy_mapped = _legacy_map_positions_to_genes(df_legacy, legacy_contig_trees)
legacy_gene_elapsed = time.time() - t0
n_mapped_leg = df_legacy_mapped["gene_id"].notna().sum()
print(f"  Elapsed: {legacy_gene_elapsed:.2f}s  |  "
      f"{n_mapped_leg:,} / {len(df_legacy_mapped):,} positions mapped to a gene")

# ── Run new gene mapping ──────────────────────────────────────────────────
# build_mag_gene_trees now accepts mags_to_include so it only builds trees
# for MAGs that have mapped reads. In a full pipeline run this is
# set(mag_contigs.keys()) — all MAGs with ≥1 covered contig. In this
# single-MAG notebook test we pass {MAG_NAME} so only one MAG's worth of
# genes (a few thousand) is processed instead of all 3.8 M genes across
# all 1,524 MAGs. This makes the timing realistic and the test fast.
print(f"\nNew gene mapping: building trees for MAGs with mapped reads ({MAG_NAME} only in this test) ...")
t0 = time.time()
mag_gene_trees    = build_mag_gene_trees(genes_df, mag_mapping, mags_to_include={MAG_NAME})
new_contig_trees  = mag_gene_trees.get(MAG_NAME, {})

# Apply lookup_gene to every position in df_legacy (same rows used above).
# Sorting the returned gene IDs normalises ordering so comma-joined strings
# are directly comparable to the legacy output.
def _normalise_gene_id(gid):
    """Sort comma-joined gene IDs for a deterministic comparison string."""
    if not gid:
        return None
    parts = [p.strip() for p in gid.split(",")]
    return ",".join(sorted(parts))

df_new_mapped = df_legacy.copy()
df_new_mapped["gene_id"] = [
    _normalise_gene_id(lookup_gene(new_contig_trees, row.contig, row.position))
    for row in df_legacy.itertuples()
]
new_gene_elapsed = time.time() - t0
n_mapped_new = df_new_mapped["gene_id"].notna().sum()
print(f"  Elapsed: {new_gene_elapsed:.2f}s  |  "
      f"{n_mapped_new:,} / {len(df_new_mapped):,} positions mapped to a gene")

# ── Compare gene_id columns ───────────────────────────────────────────────
# Sort both DataFrames so row i in df_leg_gene aligns with row i in df_new_gene.
# Normalise legacy gene_ids the same way (sorted parts) before comparing,
# then fill None → "" to match the production TSV format (empty string for
# intergenic positions).
df_leg_gene = (
    df_legacy_mapped
    .assign(gene_id=df_legacy_mapped["gene_id"].apply(_normalise_gene_id))
    .sort_values(["contig", "position"])
    .reset_index(drop=True)
    .fillna({"gene_id": ""})
)
df_new_gene = (
    df_new_mapped
    .sort_values(["contig", "position"])
    .reset_index(drop=True)
    .fillna({"gene_id": ""})
)

mismatches = (df_leg_gene["gene_id"] != df_new_gene["gene_id"]).sum()
total      = len(df_leg_gene)
print(f"\nGene-mapping comparison on {total:,} positions:")
print(f"  Positions mapped to a gene — legacy: {n_mapped_leg:,}  new: {n_mapped_new:,}")

if mismatches == 0:
    print("  [OK] gene_id: 0 mismatches — PERFECT MATCH!")
else:
    pct = mismatches / total * 100
    print(f"  [FAIL] gene_id: {mismatches:,} mismatches ({pct:.4f}%)")
    bad_mask = df_leg_gene["gene_id"] != df_new_gene["gene_id"]
    sample = df_leg_gene[bad_mask][["contig", "position"]].copy()
    sample["legacy_gene_id"] = df_leg_gene.loc[bad_mask, "gene_id"].values
    sample["new_gene_id"]    = df_new_gene.loc[bad_mask, "gene_id"].values
    print(sample.head(5).to_string(index=False))

Loaded 3,842,165 genes from Prodigal FASTA

Legacy gene mapping: 3,964 genes for MRGM_0050
  Elapsed: 0.28s  |  33,481 / 38,820 positions mapped to a gene

New gene mapping: building trees for MAGs with mapped reads (MRGM_0050 only in this test) ...
  Elapsed: 99.16s  |  33,481 / 38,820 positions mapped to a gene

Gene-mapping comparison on 38,820 positions:
  Positions mapped to a gene — legacy: 33,481  new: 33,481
  [OK] gene_id: 0 mismatches — PERFECT MATCH!